name: PR Workflow

on:
  pull_request:
    branches:
      - develop
      - production

jobs:
  PR:
    if: ${{ !contains(toJson(github.event.pull_request.labels), '[Skip] CI') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Enable node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Lint types and code
        run: yarn lint

      - name: Set up firebase config
        run: |
          echo 'NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyBgpWL59aHi9J4N68tVXgcWo9Ub3h63B"' >> .env
          echo 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="test-124798.firebaseapp.com"' >> .env
          echo 'NEXT_PUBLIC_FIREBASE_PROJECT_ID="stest-124798"' >> .env
          echo 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="test-124798.appspot.com"' >> .env
          echo 'NEXT_PUBLIC_FIREBASE_APP_ID="1:26163354511:web:c0259a3597b682f05b89fa"' >> .env

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test
